[build]
  publish = "/"
  command = "echo 'No build command needed - static site'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://election-explorer-backend.onrender.com/api/:splat"
  status = 200
  force = true
